const express = require('express');
const router = express.Router();
const { recordTelemetryEvent } = require('../controllers/analyticsController');
const { successResponse } = require('../utils/responseHandler');

// Health check for the analytics router
router.get('/health', (req, res) => {
    return successResponse(res, 'Analytics router is running.');
});

/**
 * @swagger
 * /api/analytics/events:
 *   post:
 *     summary: Record a new telemetry event
 *     description: >
 *       Receives and stores a single telemetry event from a game or user session.
 *       The `id` for the event is generated by the server.
 *     tags: [Analytics]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - game_id
 *               - event_type
 *             properties:
 *               game_id:
 *                 type: string
 *                 format: uuid
 *                 description: The ID of the game sending the event.
 *               session_id:
 *                 type: string
 *                 format: uuid
 *                 description: The ID of the current game session.
 *               user_id:
 *                 type: string
 *                 format: uuid
 *                 description: The ID of the user associated with the event.
 *               event_type:
 *                 type: string
 *                 description: The name of the event (e.g., 'level_start', 'item_purchased').
 *               payload:
 *                 type: object
 *                 description: A JSON object containing event-specific data.
 *                 additionalProperties: true
 *     responses:
 *       '201':
 *         description: Event recorded successfully.
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/SuccessResponse'
 *       '400':
 *         description: Bad Request - Missing required fields.
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/ErrorResponse'
 *       '500':
 *         description: Internal Server Error.
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/ErrorResponse'
 */
router.post('/events', recordTelemetryEvent);

module.exports = router;
